preload = ~/.dotfiles/wallpaper/Jason_and_Lucia_Robbery_landscape.jpg
preload = ~/.dotfiles/wallpaper/Real_Dimez_portrait.jpg

wallpaper = DP-1, ~/.dotfiles/wallpaper/Jason_and_Lucia_Robbery_landscape.jpg
wallpaper = HDMI-A-1, ~/.dotfiles/wallpaper/Real_Dimez_portrait.jpg

splash = false
ipc = on
