#!/bin/bash
# github.com/mamutal91

readonly PACKAGES=(
  alacritty alsa alsa-firmware alsa-utils android-tools archlinux-keyring atom
  bbswitch bluez bluez-libs bluez-tools bluez-utils bumblebee
  compton cronie
  dunst dhcpcd
  feh ffmpeg filezilla
  galculator git gparted gpicview gvfs gvfs-mtp
  i3-gaps i3lock
  imagemagick
  jsoncpp
  lib32-libvdpau lib32-nvidia-utils lib32-opencl-nvidia lib32-virtualgl lxappearance
  maim mesa mpd mpv
  nano nano-syntax-highlighting neofetch ntfs-3g numlockx nvidia nvidia-settings nvidia-utils
  opencl-nvidia openssh
  papirus-icon-theme peek pinta pulseaudio pulseaudio-bluetooth pulseeffects python-setuptools
  qbittorrent qt5-connectivity
  reflector rofi
  sbc scrot steam stow
  telegram-desktop terminus-font thunar thunar-archive-plugin thunar-media-tags-plugin thunar-volman ttf-liberation
  unrar unzip
  wget winetricks wireless_tools
  xclip xf86-video-intel xorg-server xorg-xbacklight xorg-xinit xorg-xprop xorg-xrandr
  zsh
)

readonly AUR=(
  capitaine-cursors
  ferdi-bin
  google-chrome grive-git
  jre8-openjdk
  noto-fonts-emoji-blob nvidia-xrun
  oh-my-zsh-git
  polybar python-ruamel-yaml
  ttf-dejavu ttf-font-awesome ttf-wps-fonts
  wps-office wps-office-extension-portuguese-brazilian-dictionary wps-office-mui-pt-br
  xidlehook
  zuki-themes zsh-syntax-highlighting
)

readonly AUR_POLYBAR=(
   termsyn-font siji-git ttf-ionicons
)
