###
#  KITTY CONFIGURATION FILE 3 of 4
#  https://github.com/snes19xx
####

# Typography 
font_family      CMU Typewriter Text Variable Width
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.5

# Window Layout & Padding 
placement_strategy top-left
window_padding_width 0 12 12 12
hide_window_decorations yes
confirm_os_window_close 0

# Cursor 
cursor_shape underline
cursor_underline_thickness 2.0
cursor_blink_interval 0

# Tab Bar 
tab_bar_edge top
tab_bar_style powerline
tab_separator ""
tab_bar_min_tabs 1
tab_bar_show_new_tab_button yes
tab_bar_align left
tab_bar_margin_height 0.0 0.0

# Minimal
tab_title_template " {index}: {title}"

# Mouse mappings for easy closing
mouse_map middle click grabbed,ungrabbed close_tab
mouse_map right click grabbed,ungrabbed close_tab

#  Active/Inactive Tab Colors \
active_tab_foreground   #F0ECE6
active_tab_background   #608552
active_tab_font_style   bold
inactive_tab_foreground #141719
inactive_tab_background #b7cca6
inactive_tab_font_style normal
tab_bar_background      #F0ECE6

#  Color Scheme  
background  #F0ECE6
foreground  #5c6a72

cursor                #5c6a72
cursor_text_color     #f3f5d9

selection_foreground  #5c6a72
selection_background  #f4f0d9

# Black
color0  #5c6a72
color8  #829181

# Red
color1                #c33b39
color9                #c33b39

# Green
color2                #729e5a
color10               #729e5a

# Yellow
color3                #dfa000
color11               #dfa000

# blue
color4                #3a94c5
color12               #3a94c5

# Magenta
color5                #df69ba
color13               #df69ba

# Cyan
color6                #4a6b70
color14               #4a6b70

# White
color7                #164a2b
color15               #5c6a72

#  Others
linux_display_server wayland
repaint_delay 8
input_delay 2
sync_to_monitor yes