font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

cursor_shape                block
cursor_blink_interval       0
scrollback_lines            10000
enable_audio_bell           no
window_padding_width        10
confirm_os_window_close     0
background_opacity          0.92
dynamic_background_opacity  yes
hide_window_decorations     yes

tab_bar_edge   top
tab_bar_style  powerline
tab_powerline_style slanted

map ctrl+shift+enter new_window
map ctrl+shift+t     new_tab
map ctrl+shift+w     close_window
map ctrl+equal       change_font_size all +1.0
map ctrl+minus       change_font_size all -1.0
map ctrl+0           change_font_size all 0

include current-theme.conf
