general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.89
    brightness = 0.6
    vibrancy = 0.17
}

image {
    monitor = DP-1
    path = ~/.face
    size = 140
    rounding = -1
    border_size = 3
    border_color = rgba(cba6f7ff)
    position = 0, 120
    halign = center
    valign = center
}

input-field {
    monitor = DP-1
    size = 320, 56
    outline_thickness = 2
    dots_size = 0.26
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(cba6f7ff)
    inner_color = rgba(1e1e2eee)
    font_color = rgba(cdd6f4ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##a6adc8">Senha</span>
    hide_input = false
    check_color = rgba(89b4faff)
    fail_color = rgba(f38ba8ff)
    fail_text = <span foreground="##f38ba8">Senha incorreta</span>
    rounding = 12
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(cdd6f4ff)
    font_size = 96
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 280
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    color = rgba(a6adc8ff)
    font_size = 20
    font_family = Inter
    position = 0, 200
    halign = center
    valign = center
}
