general {
    lock_cmd = ~/.dotfiles/bin/bloquear.sh
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
