monitor = DP-1, 2560x1440@180.00, 1080x240, 1
monitor = DP-2, 1920x1080@143.98, 0x0, 1, transform, 1
monitor = , preferred, auto, 1

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-2, default:true
