windowrule = workspace 9 silent, class:^(ricepanel)$
windowrule = fullscreen, class:^(ricepanel)$
windowrule = noborder, class:^(ricepanel)$
windowrule = norounding, class:^(ricepanel)$
windowrule = noshadow, class:^(ricepanel)$
windowrule = noblur, class:^(ricepanel)$
windowrule = noinitialfocus, class:^(ricepanel)$
windowrule = nofocus, class:^(ricepanel)$

windowrule = float, class:^(thunar)$, title:^(.*Propriedades.*)$
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(nwg-look)$
windowrule = float, class:^(nwg-displays)$
windowrule = float, class:^(qt6ct|qt5ct)$
windowrule = float, class:^(org.kvantum.kvantummanager)$
windowrule = float, class:^(virt-manager)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(xarchiver)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = size 640 360, title:^(Picture-in-Picture)$

windowrule = float, class:^(.*)$, title:^(Abrir arquivo|Salvar como|Selecionar pasta|Open File|Save As)$
windowrule = size 1040 651, class:^(thunar)$
windowrule = center, class:^(thunar)$

windowrule = opacity 0.94 0.94, class:^(com.mitchellh.ghostty)$
windowrule = opacity 0.96 0.96, class:^(code|Code)$

windowrule = idleinhibit fullscreen, class:^(.*)$
windowrule = immediate, class:^(steam_app.*|gamescope)$

windowrule = float, class:^(looking-glass-client)$
windowrule = fullscreen, class:^(looking-glass-client)$

layerrule = blur, waybar
layerrule = blur, fuzzel
layerrule = blur, notifications
layerrule = ignorezero, waybar
layerrule = ignorezero, fuzzel
layerrule = ignorezero, notifications
