#!/usr/bin/env bash

REPOS=(
    art
    bionic
    bootable_recovery
    build_blueprint
    development
    device_generic_goldfish
    device_generic_goldfish-opengl
    external_e2fsprogs
    external_gptfdisk
    external_guice
    external_libcxx
    external_mksh
    external_openssh
    external_tinyalsa
    external_tinycompress
    frameworks_av
    frameworks_native
    frameworks_opt_net_wifi
    frameworks_opt_telephony
    frameworks_opt_timezonepicker
    hardware_broadcom_libbt
    hardware_interfaces
    hardware_libhardware
    hardware_libhardware_legacy
    hardware_nxp_nfc
    hardware_qcom_audio
    hardware_qcom_data_ipacfg-mgr
    hardware_qcom_keymaster
    hardware_qcom_sdm845_display
    hardware_ril
    packages_apps_BasicSmsReceiver
    packages_apps_Bluetooth
    packages_apps_Camera2
    packages_apps_CarrierConfig
    packages_apps_CellBroadcastReceiver
    packages_apps_CertInstaller
    packages_apps_EmergencyInfo
    packages_apps_HTMLViewer
    packages_apps_KeyChain
    packages_apps_ManagedProvisioning
    packages_apps_Nfc
    packages_apps_PackageInstaller
    packages_apps_PhoneCommon
    packages_apps_SafetyRegulatoryInfo
    packages_apps_SecureElement
    packages_apps_SettingsIntelligence
    packages_apps_Stk
    packages_apps_StorageManager
    packages_apps_Tag
    packages_apps_Terminal
    packages_apps_ThemePicker
    packages_apps_Traceur
    packages_apps_TvSettings
    packages_apps_WallpaperPicker2
    packages_inputmethods_LatinIME
    packages_modules_CaptivePortalLogin
    packages_providers_BlockedNumberProvider
    packages_providers_BookmarkProvider
    packages_providers_CalendarProvider
    packages_providers_CallLogProvider
    packages_providers_ContactsProvider
    packages_providers_DownloadProvider
    packages_providers_MediaProvider
    packages_providers_PartnerBookmarksProvider
    packages_providers_TelephonyProvider
    packages_providers_UserDictionaryProvider
    packages_screensavers_Basic
    packages_screensavers_PhotoTable
    packages_services_BuiltInPrintService
    packages_services_Mms
    packages_services_Telecomm
    packages_services_Telephony
    packages_wallpapers_LivePicker
    prebuilts_build-tools
    prebuilts_gcc_darwin-x86_aarch64_aarch64-linux-android-4.9
    prebuilts_gcc_darwin-x86_arm_arm-linux-androideabi-4.9
    prebuilts_gcc_darwin-x86_x86_x86_64-linux-android-4.9
    prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
    prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
    prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9
    system_bt
    system_core
    system_incremental_delivery
    system_libufdt
    system_netd
    system_sepolicy
    system_tools_mkbootimg
    system_update_engine
    system_vold
    tools_metalava
    external_ant-wireless_ant_client
    external_ant-wireless_ant_native
    external_ant-wireless_ant_service
    external_ant-wireless_antradio-library
    external_ant-wireless_hidl
    external_bash
    external_connectivity
    external_exfatprogs
    external_htop
    external_json-c
    external_libncurses
    external_nano
    external_ntfs-3g
    external_p7zip
    external_pigz
    external_rsync
    external_unrar
    external_vim
    external_zip
    hardware_broadcom_nfc
    hardware_qcom-caf_common
    hardware_qcom_audio
    hardware_qcom_display
    hardware_qcom_media
    hardware_qcom_bt
    hardware_qcom_thermal
    hardware_qcom_vr
    hardware_qcom_wlan
    packages_apps_FlipFlap
    packages_apps_Profiles
    packages_apps_Seedvault
    packages_resources_devicesettings
    system_tools_dtbtool
    vendor_codeaurora_telephony
    vendor_nxp_opensource_external_libnfc-nci
    vendor_nxp_opensource_frameworks
    vendor_nxp_opensource_packages_apps_Nfc
    vendor_nxp_interfaces_opensource_nfc
    vendor_nxp_opensource_halimpl
    vendor_nxp_opensource_hidlimpl
    vendor_nxp_opensource_halimpl
    vendor_nxp_opensource_hidlimpl
    vendor_qcom_opensource_audio
    vendor_qcom_opensource_bluetooth-commonsys-intf
    vendor_qcom_opensource_bluetooth_ext
    vendor_qcom_opensource_packages_apps_Bluetooth
    vendor_qcom_opensource_system_bt
    vendor_qcom_opensource_cryptfs_hw
    vendor_qcom_opensource_data-ipa-cfg-mgr
    vendor_qcom_opensource_dataservices
    vendor_qcom_opensource_interfaces
    vendor_qcom_opensource_libfmjni
    vendor_qcom_opensource_power
    vendor_qcom_opensource_thermal-engine
    vendor_qcom_opensource_vibrator
)

REPOS_CAF=(
    hardware_qcom_bt
    hardware_qcom_wlan
)
