[appearance]
font = "Inter 10"
label_font = "JetBrainsMono Nerd Font Bold 12"
card_padding = 18.0
card_radius = 14.0
max_card_width = 380.0
max_card_height = 240.0
label_height = 28.0
thumb_padding = 8.0
select_border = 3.0

[colors]
background = "#11111bd9"
card = "#1e1e2ef2"
selection = "#cba6f7ff"
label = "#cdd6f4ff"
empty_label = "#6c7086a6"
window_label = "#bac2deee"
active_window = "#89b4fae6"

[behavior]
no_preview = false
switch_on_move = true
allow_mouse = true
ignore_monitors = ["DP-2"]
